import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Navbar} from '@/components'
import InitializeAuth from "@/components/initializeAuth"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Authentication mockup",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <InitializeAuth />
        {children}
      </body>
    </html>
  );
}
